#!/bin/bash
set -euo pipefail

# Thin experiment wrapper for the pre-projector MetricGroundedGeometryProjection path.
# The wrapped train_vsi.sh keeps repo defaults baseline-safe; this script opts in.
export MODEL_USE_GEOMETRY_AWARE_PROJECTION="${MODEL_USE_GEOMETRY_AWARE_PROJECTION:-True}"
export MODEL_SPATIAL_ENCODER_TYPE="${MODEL_SPATIAL_ENCODER_TYPE:-cut3r}"
export MODEL_GEOMETRY_POSITION_MODE="${MODEL_GEOMETRY_POSITION_MODE:-spherical}"
export MODEL_NUM_GEOMETRY_PROJECTION_LAYERS="${MODEL_NUM_GEOMETRY_PROJECTION_LAYERS:-1}"
export MODEL_GEOMETRY_PROJECTION_NUM_HEADS="${MODEL_GEOMETRY_PROJECTION_NUM_HEADS:-16}"
export MODEL_USE_AUXILIARY_GEOMETRY_HEAD="${MODEL_USE_AUXILIARY_GEOMETRY_HEAD:-True}"
export MODEL_AUX_GEOMETRY_TARGETS="${MODEL_AUX_GEOMETRY_TARGETS:-azimuth,elevation,log_distance}"
export MODEL_LAMBDA_GEO="${MODEL_LAMBDA_GEO:-0.1}"
export MODEL_GEOMETRY_LOSS_TYPE="${MODEL_GEOMETRY_LOSS_TYPE:-smooth_l1}"
export MODEL_DETACH_GEOMETRY_TARGETS="${MODEL_DETACH_GEOMETRY_TARGETS:-True}"
export MODEL_GEOMETRY_GATE_INIT="${MODEL_GEOMETRY_GATE_INIT:-0.0}"
export MODEL_USE_GEOMETRY_CONFIDENCE_MASK="${MODEL_USE_GEOMETRY_CONFIDENCE_MASK:-True}"
export MODEL_ALLOW_MISSING_GEOMETRY_TARGETS="${MODEL_ALLOW_MISSING_GEOMETRY_TARGETS:-False}"
export MODEL_GEOMETRY_POSITION_MAX_ABS="${MODEL_GEOMETRY_POSITION_MAX_ABS:-10.0}"
export MODEL_GEOMETRY_FIXED_SCENE_SCALE="${MODEL_GEOMETRY_FIXED_SCENE_SCALE:-5.0}"
export MODEL_GEOMETRY_PROJECTION_DROPOUT="${MODEL_GEOMETRY_PROJECTION_DROPOUT:-0.0}"
export MODEL_TUNE_GEOMETRY_AWARE_PROJECTION="${MODEL_TUNE_GEOMETRY_AWARE_PROJECTION:-True}"
export MODEL_TUNE_FUSION_BLOCK="${MODEL_TUNE_FUSION_BLOCK:-False}"
# NOTE: MODEL_FUSION_BLOCK is ignored when MODEL_USE_GEOMETRY_AWARE_PROJECTION=True.
# The main path is 2D visual-token self-attention with Geometry-RoPE, not fusion.
export MODEL_FUSION_BLOCK="${MODEL_FUSION_BLOCK:-svf_baseline}"
export SPATIAL_FEATURES_SUBDIR="${SPATIAL_FEATURES_SUBDIR:-spatial_features_points}"

exec bash "${TRAIN_SCRIPT:-train_vsi.sh}"
